apiVersion: apps/v1
kind: Deployment
metadata:
  name: sggc-frontend-dpl
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: sggc-frontend-pds
      labels:
        app: frontend
    spec:
      containers:
        - image: tobypeel/steamgroupgamechecker:frontend
          name: userservice
          ports:
            - containerPort: 3000