apiVersion: v1
kind: Service
metadata:
  name: sggc-frontend-svc
  labels:
    app : frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30002
      protocol: TCP
  selector:
    app : frontend