apiVersion: apps/v1
kind: Deployment
metadata:
  name: sggc-webservice-dpl
  labels:
    app: webservice
spec:
  selector:
    matchLabels:
      app: webservice
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: sggc-webservice-pds
      labels:
        app: webservice
    spec:
      containers:
        - image: tobypeel/steamgroupgamechecker:webservice
          imagePullPolicy: "Always"
          name: sggc-webservice-ctnrs
          ports:
            - containerPort: 8080