apiVersion: apps/v1
kind: Deployment
metadata:
  name: sggc-webservice-dpl
  labels:
    app: webservice
spec:
  selector:
    matchLabels:
      app: webservice
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: sggc-webservice-pds
      labels:
        app: webservice
    spec:
      containers:
        - image: tobypeel/steamgroupgamechecker:webservice
          name: userservice
          ports:
            - containerPort: 8080